export interface IPetSkillDesc
{
	id: number;
	desc: string | string[];
	levelDesc: string[];
	upgradeDesc?: string;
	maxLevel: number;
	energy: number;
	skillParam1: number;
	skillParam2: number;
	skillParamGrown: number;
}

function genLevelDesc(str: string, x0: number, dx: number, n: number)
{
	let arr = new Array(n);
	for (let i = 0; i < n; ++i)
	{
		arr[i] = str.replace('{x}', (x0 + dx * i).toString());
	}
	return arr;
}

export const PetSkillDesc: IPetSkillDesc[] = [
	{
		id: 0,
		desc: '将线型范围的精灵转化成自己',
		levelDesc: ['范围：C', '范围：B', '范围：A', '范围：S', '范围：SS', '范围：SSS'],
		maxLevel: 6,
		energy: 12,
		skillParam1: 160,
		skillParam2: 160,
		skillParamGrown: 20,
		upgradeDesc: '效果范围增大',
	},
	{
		id: 1,
		desc: '将画面中央的精灵转化成自己',
		levelDesc: ['范围：C', '范围：B', '范围：A', '范围：S', '范围：SS', '范围：SSS'],
		maxLevel: 6,
		energy: 12,
		skillParam1: 320,
		skillParam2: 320,
		skillParamGrown: 15,
		upgradeDesc: '效果范围增大',
	},
	{
		id: 2,
		desc: '随即消除一种精灵',
		levelDesc: genLevelDesc('充能数量：{x}个', 16, -1, 6),
		maxLevel: 6,
		energy: 16,
		skillParam1: 16,
		skillParam2: 16,
		skillParamGrown: -1,
		upgradeDesc: '消除数量增加',
	},
	{
		id: 3,
		desc: genLevelDesc('随机消除{x}个精灵', 14, 2, 6),
		levelDesc: genLevelDesc('消除数量：{x}个', 14, 1, 6),
		maxLevel: 6,
		energy: 12,
		skillParam1: 14,
		skillParam2: 14,
		skillParamGrown: 1,
		upgradeDesc: '消除数量增加',
	},
	{
		id: 4,
		desc: '消除画面中央的精灵',
		levelDesc: ['范围：C', '范围：B', '范围：A', '范围：S', '范围：SS', '范围：SSS'],
		maxLevel: 6,
		energy: 12,
		skillParam1: 300,
		skillParam2: 300,
		skillParamGrown: 15,
		upgradeDesc: '效果范围增大',
	},
	{
		id: 5,
		desc: '消除画面两列精灵',
		levelDesc: ['范围：C', '范围：B', '范围：A', '范围：S', '范围：SS', '范围：SSS'],
		maxLevel: 6,
		energy: 12,
		skillParam1: 70,
		skillParam2: 70,
		skillParamGrown: 8,
		upgradeDesc: '效果范围增大',
	},
	{
		id: 6,
		desc: '消除线状范围的精灵',
		levelDesc: ['范围：C', '范围：B', '范围：A', '范围：S', '范围：SS', '范围：SSS'],
		maxLevel: 6,
		energy: 12,
		skillParam1: 150,
		skillParam2: 150,
		skillParamGrown: 15,
		upgradeDesc: '效果范围增大',
	},
	{
		id: 7,
		desc: '消除×形状范围的精灵',
		levelDesc: ['范围：C', '范围：B', '范围：A', '范围：S', '范围：SS', '范围：SSS'],
		maxLevel: 6,
		energy: 12,
		skillParam1: 60,
		skillParam2: 60,
		skillParamGrown: 7,
		upgradeDesc: '效果范围增大',
	},
	{
		id: 8,
		desc: genLevelDesc('延长{x}秒倒计时', 3, 0.5, 6),
		levelDesc: genLevelDesc('延长时间：{x}秒', 3, 0.5, 4),
		maxLevel: 4,
		energy: 16,
		skillParam1: 3,
		skillParam2: 3,
		skillParamGrown: 0.5,
		upgradeDesc: '延长时间增长',
	},
	{
		id: 9,
		desc: ['随机转化出2~3个炸弹', '随机转化出3~4个炸弹', '随机转化出4~5个炸弹', '随机转化出5~6个炸弹', '随机转化出6~7个炸弹', '随机转化出7~8个炸弹'],
		levelDesc: ['转化数量：2~3个', '转化数量：3~4个', '转化数量：4~5个', '转化数量：5~6个', '转化数量：6~7个', '转化数量：7~8个'],
		maxLevel: 6,
		energy: 12,
		skillParam1: 2,
		skillParam2: 3,
		skillParamGrown: 1,
		upgradeDesc: '转化数量增加',
	},
	{
		id: 10,
		desc: genLevelDesc('{x}秒内最低连接精灵数量降为1', 4, 0.5, 6),
		levelDesc: genLevelDesc('持续时间：{x}秒', 4, 0.5, 6),
		maxLevel: 6,
		energy: 12,
		skillParam1: 4,
		skillParam2: 4,
		skillParamGrown: 0.5,
		upgradeDesc: '持续时间增长',
	},
	{
		id: 11,
		desc: '下次连接无视精灵种类',
		levelDesc: genLevelDesc('最高长度：{x}个', 14, 1, 6),
		maxLevel: 6,
		energy: 12,
		skillParam1: 14,
		skillParam2: 14,
		skillParamGrown: 1,
		upgradeDesc: '连接上限增加',
	},
	{
		id: 12,
		desc: '消除指定列的精灵',
		levelDesc: ['范围：C', '范围：B', '范围：A', '范围：S', '范围：SS', '范围：SSS'],
		maxLevel: 6,
		energy: 12,
		skillParam1: 160,
		skillParam2: 160,
		skillParamGrown: 20,
		upgradeDesc: '效果范围增大',
	},
	{
		id: 13,
		desc: 'todotodotodo',
		levelDesc: genLevelDesc('最高长度：{x}个', 14, 1, 6),
		maxLevel: 6,
		energy: 12,
		skillParam1: 14,
		skillParam2: 14,
		skillParamGrown: 1,
		upgradeDesc: '',
	},
	{
		id: 14,
		desc: genLevelDesc('减缓{x}秒时间', 3, 0.5, 6),
		levelDesc: genLevelDesc('持续时间：{x}个', 4, 1, 6),
		maxLevel: 6,
		energy: 12,
		skillParam1: 3,
		skillParam2: 3,
		skillParamGrown: 0.5,
		upgradeDesc: '持续时间增长',
	},
	{
		id: 15,
		desc: '随机将一种精灵抓到最上方',
		levelDesc: genLevelDesc('充能数量：{x}个', 16, -1, 6),
		maxLevel: 6,
		energy: 12,
		skillParam1: 16,
		skillParam2: 16,
		skillParamGrown: -1,
		upgradeDesc:'激活所需精灵减少',
	},
	{
		id: 16,
		desc: genLevelDesc('{x}秒内所获金币翻倍', 6, 1, 6),
		levelDesc: genLevelDesc('持续时间：{x}秒', 6, 1, 6),
		maxLevel: 6,
		energy: 12,
		skillParam1: 6,
		skillParam2: 6,
		skillParamGrown: 1,
		upgradeDesc:'持续时间增长',
	},
	{
		id: 17,
		desc: '消除画面下方精灵',
		levelDesc: ['范围：C', '范围：B', '范围：A', '范围：S', '范围：SS', '范围：SSS'],
		maxLevel: 6,
		energy: 12,
		skillParam1: 150,
		skillParam2: 150,
		skillParamGrown: 15,
		upgradeDesc:'效果范围增大',
	},
	{
		id: 18,
		desc: genLevelDesc('{x}秒内连线周围的果冻会被一并消除', 3, 0.5, 6),
		levelDesc: genLevelDesc('持续时间：{x}秒', 3, 0.5, 6),
		maxLevel: 6,
		energy: 12,
		skillParam1: 3,
		skillParam2: 3,
		skillParamGrown: 0.5,
		upgradeDesc:'持续时间增长',
	},
	{
		id: 19,
		desc: '充能fever条',
		levelDesc: genLevelDesc('充能数量：{x}个', 16, -1, 6),
		maxLevel: 6,
		energy: 12,
		skillParam1: 16,
		skillParam2: 16,
		skillParamGrown: -1,
		upgradeDesc:'激活所需精灵减少',
	},
	{
		id: 20,
		desc: '转化出可以引爆的爆蛋',
		levelDesc: genLevelDesc('出现数量：{x}个', 2, 1, 6),
		maxLevel: 6,
		energy: 12,
		skillParam1: 2,
		skillParam2: 2,
		skillParamGrown: 1,
		upgradeDesc:'转化数量增加',
	}
]